[package]
name = "sokudo-core"
version = "0.1.0"
edition = "2021"

[dependencies]
parry3d.workspace = true
sokudo-io.workspace = true

glam.workspace = true
thiserror.workspace = true

[features]
inspect = []
