[package]
name = "sokudo-io"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
glam.workspace = true
thiserror.workspace = true
parry3d.workspace = true

ron = "0.8.1"

[features]
inspect = []
