[package]
name = "sokudo-playback"
version = "0.1.0"
edition = "2021"

[dependencies]
sokudo-io.workspace = true
thiserror.workspace = true
glam.workspace = true
bevy = { version = "0.14.2", features = ["dynamic_linking"] }
bevy_mod_picking = "0.20.1"

[features]
inspect = []
